#include <boost/shared_ptr.hpp>
class FakeGripper;
typedef boost::shared_ptr<FakeGripper> FakeGripperPtr;
class FakeObjectCopy;
typedef boost::shared_ptr<FakeObjectCopy> FakeObjectCopyPtr;
class ScreenRecorder;
typedef boost::shared_ptr<ScreenRecorder> ScreenRecorderPtr;
class ScreenCapture;
typedef boost::shared_ptr<ScreenCapture> ScreenCapturePtr;
class ScreenThreadRecorder;
typedef boost::shared_ptr<ScreenThreadRecorder> ScreenThreadRecorderPtr;
class ConsecutiveImageWriter;
typedef boost::shared_ptr<ConsecutiveImageWriter> ConsecutiveImageWriterPtr;
class BulletSoftObject;
typedef boost::shared_ptr<BulletSoftObject> BulletSoftObjectPtr;
class RaveInstance;
typedef boost::shared_ptr<RaveInstance> RaveInstancePtr;
class RaveRobotObject;
typedef boost::shared_ptr<RaveRobotObject> RaveRobotObjectPtr;
class ScopedRobotSave;
typedef boost::shared_ptr<ScopedRobotSave> ScopedRobotSavePtr;
class PlotObject;
typedef boost::shared_ptr<PlotObject> PlotObjectPtr;
class PlotPoints;
typedef boost::shared_ptr<PlotPoints> PlotPointsPtr;
class PlotLines;
typedef boost::shared_ptr<PlotLines> PlotLinesPtr;
class PlotSpheres;
typedef boost::shared_ptr<PlotSpheres> PlotSpheresPtr;
class PlotBoxes;
typedef boost::shared_ptr<PlotBoxes> PlotBoxesPtr;
class PlotAxes;
typedef boost::shared_ptr<PlotAxes> PlotAxesPtr;
class ConvexDecomp;
typedef boost::shared_ptr<ConvexDecomp> ConvexDecompPtr;
class Scene;
typedef boost::shared_ptr<Scene> ScenePtr;
class BulletObject;
typedef boost::shared_ptr<BulletObject> BulletObjectPtr;
class BulletConstraint;
typedef boost::shared_ptr<BulletConstraint> BulletConstraintPtr;
class GrabberKinematicObject;
typedef boost::shared_ptr<GrabberKinematicObject> GrabberKinematicObjectPtr;
class PlaneStaticObject;
typedef boost::shared_ptr<PlaneStaticObject> PlaneStaticObjectPtr;
class CylinderStaticObject;
typedef boost::shared_ptr<CylinderStaticObject> CylinderStaticObjectPtr;
class SphereObject;
typedef boost::shared_ptr<SphereObject> SphereObjectPtr;
class BoxObject;
typedef boost::shared_ptr<BoxObject> BoxObjectPtr;
class CapsuleObject;
typedef boost::shared_ptr<CapsuleObject> CapsuleObjectPtr;
class CapsuleObjectY;
typedef boost::shared_ptr<CapsuleObjectY> CapsuleObjectYPtr;
class OSGInstance;
typedef boost::shared_ptr<OSGInstance> OSGInstancePtr;
class BulletInstance;
typedef boost::shared_ptr<BulletInstance> BulletInstancePtr;
class EnvironmentObject;
typedef boost::shared_ptr<EnvironmentObject> EnvironmentObjectPtr;
class Environment;
typedef boost::shared_ptr<Environment> EnvironmentPtr;
class Fork;
typedef boost::shared_ptr<Fork> ForkPtr;
class Action;
typedef boost::shared_ptr<Action> ActionPtr;
