#pragma once
#include <boost/shared_ptr.hpp>
class CoordinateTransformer;
typedef boost::shared_ptr<CoordinateTransformer> CoordinateTransformerPtr;
class ImageTopicRecorder;
typedef boost::shared_ptr<ImageTopicRecorder> ImageTopicRecorderPtr;
class TrackedObject;
typedef boost::shared_ptr<TrackedObject> TrackedObjectPtr;
class TrackedRope;
typedef boost::shared_ptr<TrackedRope> TrackedRopePtr;
class TrackedCloth;
typedef boost::shared_ptr<TrackedCloth> TrackedClothPtr;
class TrackedTowel;
typedef boost::shared_ptr<TrackedTowel> TrackedTowelPtr;
class TrackedSponge;
typedef boost::shared_ptr<TrackedSponge> TrackedSpongePtr;
class TrackedBox;
typedef boost::shared_ptr<TrackedBox> TrackedBoxPtr;
class FeatureExtractor;
typedef boost::shared_ptr<FeatureExtractor> FeatureExtractorPtr;
class CloudFeatureExtractor;
typedef boost::shared_ptr<CloudFeatureExtractor> CloudFeatureExtractorPtr;
class TrackedObjectFeatureExtractor;
typedef boost::shared_ptr<TrackedObjectFeatureExtractor> TrackedObjectFeatureExtractorPtr;
class GrabDetector;
typedef boost::shared_ptr<GrabDetector> GrabDetectorPtr;
class GrabManager;
typedef boost::shared_ptr<GrabManager> GrabManagerPtr;
class SimplePhysicsTracker;
typedef boost::shared_ptr<SimplePhysicsTracker> SimplePhysicsTrackerPtr;
class DemoRecorder;
typedef boost::shared_ptr<DemoRecorder> DemoRecorderPtr;
class VisibilityInterface;
typedef boost::shared_ptr<VisibilityInterface> VisibilityInterfacePtr;
class EverythingIsVisible;
typedef boost::shared_ptr<EverythingIsVisible> EverythingIsVisiblePtr;
class DepthImageVisibility;
typedef boost::shared_ptr<DepthImageVisibility> DepthImageVisibilityPtr;
class OSGVisibility;
typedef boost::shared_ptr<OSGVisibility> OSGVisibilityPtr;
class BulletRaycastVisibility;
typedef boost::shared_ptr<BulletRaycastVisibility> BulletRaycastVisibilityPtr;
class AllOcclusionsVisibility;
typedef boost::shared_ptr<AllOcclusionsVisibility> AllOcclusionsVisibilityPtr;
class MultiVisibility;
typedef boost::shared_ptr<MultiVisibility> MultiVisibilityPtr;
class PointCloudPlot;
typedef boost::shared_ptr<PointCloudPlot> PointCloudPlotPtr;
class PhysicsTracker;
typedef boost::shared_ptr<PhysicsTracker> PhysicsTrackerPtr;
class PhysicsTrackerVisualizer;
typedef boost::shared_ptr<PhysicsTrackerVisualizer> PhysicsTrackerVisualizerPtr;
class CamSync;
typedef boost::shared_ptr<CamSync> CamSyncPtr;
class TrackedCompound;
typedef boost::shared_ptr<TrackedCompound> TrackedCompoundPtr;
class MultiHypTracker;
typedef boost::shared_ptr<MultiHypTracker> MultiHypTrackerPtr;
