
ExprVector exprAdd(const ExprVector& a, const ExprVector& b);
ExprVector exprSub(const ExprVector& a, const ExprVector& b);
QExprVector exprMult(const ExprVector& a, const ExprVector& b);
ExprVector exprAdd(const ExprVector& a, const VarVector& b);
ExprVector exprSub(const ExprVector& a, const VarVector& b);
QExprVector exprMult(const ExprVector& a, const VarVector& b);
ExprVector exprAdd(const ExprVector& a, const VectorXd& b);
ExprVector exprSub(const ExprVector& a, const VectorXd& b);
ExprVector exprMult(const ExprVector& a, const VectorXd& b);
ExprVector exprAdd(const VarVector& a, const ExprVector& b);
ExprVector exprSub(const VarVector& a, const ExprVector& b);
QExprVector exprMult(const VarVector& a, const ExprVector& b);
ExprVector exprAdd(const VarVector& a, const VarVector& b);
ExprVector exprSub(const VarVector& a, const VarVector& b);
QExprVector exprMult(const VarVector& a, const VarVector& b);
ExprVector exprAdd(const VarVector& a, const VectorXd& b);
ExprVector exprSub(const VarVector& a, const VectorXd& b);
ExprVector exprMult(const VarVector& a, const VectorXd& b);
ExprVector exprAdd(const VectorXd& a, const ExprVector& b);
ExprVector exprSub(const VectorXd& a, const ExprVector& b);
ExprVector exprMult(const VectorXd& a, const ExprVector& b);
ExprVector exprAdd(const VectorXd& a, const VarVector& b);
ExprVector exprSub(const VectorXd& a, const VarVector& b);
ExprVector exprMult(const VectorXd& a, const VarVector& b);
ExprVector exprAdd(const ExprVector& a, const double& b);
ExprVector exprSub(const ExprVector& a, const double& b);
ExprVector exprMult(const ExprVector& a, const double& b);
ExprVector exprAdd(const ExprVector& a, const GRBVar& b);
ExprVector exprSub(const ExprVector& a, const GRBVar& b);
QExprVector exprMult(const ExprVector& a, const GRBVar& b);
ExprVector exprAdd(const VarVector& a, const double& b);
ExprVector exprSub(const VarVector& a, const double& b);
ExprVector exprMult(const VarVector& a, const double& b);
ExprVector exprAdd(const VarVector& a, const GRBVar& b);
ExprVector exprSub(const VarVector& a, const GRBVar& b);
QExprVector exprMult(const VarVector& a, const GRBVar& b);
ExprVector exprAdd(const VectorXd& a, const GRBVar& b);
ExprVector exprSub(const VectorXd& a, const GRBVar& b);
ExprVector exprMult(const VectorXd& a, const GRBVar& b);
ExprVector exprInc(ExprVector& a, const ExprVector& b);
ExprVector exprDec(ExprVector& a, const ExprVector& b);
ExprVector exprInc(ExprVector& a, const VarVector& b);
ExprVector exprDec(ExprVector& a, const VarVector& b);
ExprVector exprInc(ExprVector& a, const VectorXd& b);
ExprVector exprDec(ExprVector& a, const VectorXd& b);
ExprVector exprInc(ExprVector& a, const double& b);
ExprVector exprDec(ExprVector& a, const double& b);
ExprVector exprInc(ExprVector& a, const GRBVar& b);
ExprVector exprDec(ExprVector& a, const GRBVar& b);
