string manip                    # manipulator description (which dofs to use)
string task                     # task description
string xmlstring                  # openrave format xml file
sensor_msgs/PointCloud2 cloud   # point cloud collision map

float64[] robot_joints          # openrave order
float64[] robot_transform		# qx, qy, qz, qw, x, y, z
float64[] goal
# cart goal: qx, qy, qz, qw, x, y, z
# joint goal: ...
# cart_follow: n x 7 list

---

float64[] trajectory            # num timesteps x num dofs (row major)